### ISSUE TITLE
Use backwards compatible switch and spinner

### ISSUE THREAD

**Issue by ZacSweers** [ZacSweers/FlashNotifier#5]
They're not compatible < API 11

**Comment by teracross** [comment]
for the switch, we may need to implement a custom toggle button? Looking into more options, but here's what I've found so far: http://stackoverflow.com/questions/9752760/slide-toggle-for-android. Still looking into spinners.

**Comment by ZacSweers** [comment]
Why would we want it to look like iOS...?

**Comment by teracross** [comment]
What I was trying to say is that we may need something similar to this. Not necessarily this exactly, will keep looking.

**Comment by ZacSweers** [comment]
We can just include the Switch and Spinner code directly from Android, which is open source.

http://stackoverflow.com/questions/16238588/can-i-use-switch-widget-with-actionbarsherlock
